# Generated by Django 3.2.9 on 2022-08-06 14:01

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_wine_thumbnail"),
    ]

    operations = [TrigramExtension(), BtreeGinExtension()]
